no not set network parameters

diff --git a/src/ports/linux/set_network_parameters b/src/ports/linux/set_network_parameters
--- a/src/ports/linux/set_network_parameters
+++ b/src/ports/linux/set_network_parameters
@@ -47,43 +47,42 @@ echo "Network script for ${INTERFACE}: " \
 
 # There is no need to set the changes permanently,
 # as the p-net stack will set the IP parameters on each start.
-# You are however free to use it if you like.
-
-if ! ip address flush label $INTERFACE; then
-   echo "Failed to flush network interface"
-   exit 1
-fi
-
-if ! ip address add $IP_ADDRESS/$NETMASK dev $INTERFACE; then
-   echo "Failed to set IP address and netmask"
-   exit 1
-fi
-
-if ! ip link set dev $INTERFACE up; then
-   echo "Failed to set network interface up"
-   exit 1
-fi
-
-if [ "${DEFAULT_GATEWAY}" != "0.0.0.0" ]; then
-   if ! ip route add default via $DEFAULT_GATEWAY; then
-      echo "Failed to set default gateway"
-      exit 1
-   fi
-else
-   echo "No valid default gateway given. Skipping setting default gateway."
-fi
-
-if [ "$SKIP_SETTING_HOSTNAME" = false ]; then
-   if ! hostname $HOSTNAME; then
-      echo "Failed to set hostname to $HOSTNAME"
-      hostname_len=${#HOSTNAME}
-      if [ $hostname_len -gt 64 ]; then
-         echo "The given hostname length is ${hostname_len} characters." \
-         "Many Linux systems have a limit of 64 characters. The p-net stack uses" \
-         "a longer stationname internally."
-      fi
-      exit 1
-   fi
-fi
+# You are however free to use it if you like
+#if ! ip address flush label $INTERFACE; then
+#   echo "Failed to flush network interface"
+#   exit 1
+#fi
+#
+#if ! ip address add $IP_ADDRESS/$NETMASK dev $INTERFACE; then
+#   echo "Failed to set IP address and netmask"
+#   exit 1
+#fi
+#
+#if ! ip link set dev $INTERFACE up; then
+#   echo "Failed to set network interface up"
+#   exit 1
+#fi
+#
+#if [ "${DEFAULT_GATEWAY}" != "0.0.0.0" ]; then
+#   if ! ip route add default via $DEFAULT_GATEWAY; then
+#      echo "Failed to set default gateway"
+#      exit 1
+#   fi
+#else
+#   echo "No valid default gateway given. Skipping setting default gateway."
+#fi
+#
+#if [ "$SKIP_SETTING_HOSTNAME" = false ]; then
+#   if ! hostname $HOSTNAME; then
+#      echo "Failed to set hostname to $HOSTNAME"
+#      hostname_len=${#HOSTNAME}
+#      if [ $hostname_len -gt 64 ]; then
+#         echo "The given hostname length is ${hostname_len} characters." \
+#         "Many Linux systems have a limit of 64 characters. The p-net stack uses" \
+#         "a longer stationname internally."
+#      fi
+#      exit 1
+#   fi
+#fi
 
 exit 0
